<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReportSidebarSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

         $items = [
             [
                 'item_key' => 'reports.forecast_history',
                 'label_en' => 'Forecast Report',
                 'label_ar' => 'تقرير التوقعات',
                 'url' => '/reports/forecast-history',
                 'icon' => 'TrendingUp',
                 'parent_key' => 'reports',
                 'order' => 1,
                 'active_route_patterns' => json_encode(['reports/forecast-history*']),
                 'permission' => 'reports.forecast',
                 'is_visible' => true,
                 'is_beta' => false,
                 'is_external' => false,
                 'module' => 'reports',
                 'device_visibility' => 'all',
                 'created_at' => $now,
                 'updated_at' => $now,
             ],
             [
                 'item_key' => 'reports.no_show',
                 'label_en' => 'No-Show Report',
                 'label_ar' => 'تقرير عدم الحضور',
                 'url' => '/reports/no-show',
                 'icon' => 'XCircle',
                 'parent_key' => 'reports',
                 'order' => 2,
                 'active_route_patterns' => json_encode(['reports/no-show*']),
                 'permission' => 'reports.noshow',
                 'is_visible' => true,
                 'is_beta' => false,
                 'is_external' => false,
                 'module' => 'reports',
                 'device_visibility' => 'all',
                 'created_at' => $now,
                 'updated_at' => $now,
             ],
             [
                 'item_key' => 'reports.cancellation',
                 'label_en' => 'Cancellation Report',
                 'label_ar' => 'تقرير الإلغاء',
                 'url' => '/reports/cancellation',
                 'icon' => 'XCircle',
                 'parent_key' => 'reports',
                 'order' => 3,
                 'active_route_patterns' => json_encode(['reports/cancellation*']),
                 'permission' => 'reports.cancellation',
                 'is_visible' => true,
                 'is_beta' => false,
                 'is_external' => false,
                 'module' => 'reports',
                 'device_visibility' => 'all',
                 'created_at' => $now,
                 'updated_at' => $now,
             ],
             [
                 'item_key' => 'reports.commission',
                 'label_en' => 'Commission Report',
                 'label_ar' => 'تقرير العمولات',
                 'url' => '/reports/commission',
                 'icon' => 'Currency',
                 'parent_key' => 'reports',
                 'order' => 4,
                 'active_route_patterns' => json_encode(['reports/commission*']),
                 'permission' => 'reports.commission',
                 'is_visible' => true,
                 'is_beta' => false,
                 'is_external' => false,
                 'module' => 'reports',
                 'device_visibility' => 'all',
                 'created_at' => $now,
                 'updated_at' => $now,
             ],
             [
                 'item_key' => 'reports.housekeeping_discrepancy',
                 'label_en' => 'HK Discrepancy',
                 'label_ar' => 'اختلافات housekeeping',
                 'url' => '/reports/housekeeping-discrepancy',
                 'icon' => 'ExclamationTriangle',
                 'parent_key' => 'reports',
                 'order' => 5,
                 'active_route_patterns' => json_encode(['reports/housekeeping-discrepancy*']),
                 'permission' => 'reports.housekeeping_discrepancy',
                 'is_visible' => true,
                 'is_beta' => false,
                 'is_external' => false,
                 'module' => 'reports',
                 'device_visibility' => 'all',
                 'created_at' => $now,
                 'updated_at' => $now,
             ],
             [
                 'item_key' => 'reports.adr_revpar',
                 'label_en' => 'ADR & RevPAR',
                 'label_ar' => 'الADR و RevPAR',
                 'url' => '/reports/adr-revpar',
                 'icon' => 'ChartBar',
                 'parent_key' => 'reports',
                 'order' => 6,
                 'active_route_patterns' => json_encode(['reports/adr-revpar*']),
                 'permission' => 'reports.adr',
                 'is_visible' => true,
                 'is_beta' => false,
                 'is_external' => false,
                 'module' => 'reports',
                 'device_visibility' => 'all',
                 'created_at' => $now,
                 'updated_at' => $now,
             ],
             [
                 'item_key' => 'reports.custom',
                 'label_en' => 'Custom Reports',
                 'label_ar' => 'تقارير مخصصة',
                 'url' => '/reports/custom-reports',
                 'icon' => 'Table',
                 'parent_key' => 'reports',
                 'order' => 7,
                 'active_route_patterns' => json_encode(['reports/custom-reports*']),
                 'permission' => 'reports.custom_create',
                 'is_visible' => true,
                 'is_beta' => false,
                 'is_external' => false,
                 'module' => 'reports',
                 'device_visibility' => 'all',
                 'created_at' => $now,
                 'updated_at' => $now,
             ],
             [
                 'item_key' => 'reports.schedules',
                 'label_en' => 'Scheduled Reports',
                 'label_ar' => 'تقارير مجدولة',
                 'url' => '/reports/report-schedules',
                 'icon' => 'Calendar',
                 'parent_key' => 'reports',
                 'order' => 8,
                 'active_route_patterns' => json_encode(['reports/report-schedules*']),
                 'permission' => 'reports.schedule_create',
                 'is_visible' => true,
                 'is_beta' => false,
                 'is_external' => false,
                 'module' => 'reports',
                 'device_visibility' => 'all',
                 'created_at' => $now,
                 'updated_at' => $now,
             ],
         ];

        foreach ($items as $item) {
            DB::table('sidebar_items')->updateOrInsert(
                ['item_key' => $item['item_key']],
                $item
            );
        }
    }
}