#!/usr/bin/env php
<?php

error_reporting(E_ALL);
ini_set('display_errors', '1');

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

echo "autoload ok\n";

$app = require_once __DIR__.'/bootstrap/app.php';

echo "bootstrap ok\n";

$status = $app->handleCommand(new ArgvInput);

echo "command handled: {$status}\n";

exit($status);