<?php

namespace App;

use App\Traits\HasTeam;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Watson\Rememberable\Rememberable;
use App\Scopes\TeamScope;

class Activity extends \Spatie\Activitylog\Models\Activity
{
    use Rememberable;
    use HasTeam;

    // protected static function boot()
    // {
    //     parent::boot();
    //     static::addGlobalScope(new TeamScope());
    // }

//    public function causer(): MorphTo
//    {
//        return parent::causer(); // TODO: Change the autogenerated stub
//    }
}
