import {
  LayoutDashboard,
  Users,
  UserCircle,
  Activity,
  BadgePercent,
  BriefcaseBusiness,
  CalendarCheck2,
  BookOpenCheck,
  CalendarRange,
  CalendarDays,
  ConciergeBell,
  LogIn,
  BedDouble,
  LogOut,
  Monitor,
  Hotel,
  DoorOpen,
  Sparkles,
  Ban,
  Wallet,
  Receipt,
  Landmark,
  MoonStar,
  CircleDollarSign,
  BarChart3,
  FileText,
  Download,
  Upload,
  Shield,
  UsersRound,
  BellRing,
  Calendar,
  Building2,
  PieChart,
  BrushCleaning,
  Wrench,
  RefreshCcw,
  Scale,
  FileBadge,
  Sun,
  Boxes,
  Cable,
  LifeBuoy,
  Settings,
  SlidersHorizontal,
  Cog,
  Building,
  Bath,
  Plug,
  UserCog,
  FileCheck2,
  Bell,
  HandCoins,
  ClipboardList,
  Hash,
  Link,
  Globe,
  Star,
  Hammer,
} from 'lucide-vue-next';

export const sidebarConfig = [
  { label: 'Dashboard', route: 'dashboard', path: '/dashboard', icon: LayoutDashboard, permission: 'view dashboard' },
  {
    label: 'Client Relations',
    icon: Users,
    children: [
      { label: 'Profiles', route: 'client-relations.profiles', path: '/client-relations/profiles', icon: UserCircle, permission: 'manage profiles' },
      { label: 'Activities', route: 'client-relations.activities', path: '/client-relations/activities', icon: Activity, permission: 'manage activities' },
      { label: 'Memberships', route: 'client-relations.memberships', path: '/client-relations/memberships', icon: BadgePercent, permission: 'manage memberships' },
      { label: 'Sales', route: 'client-relations.sales', path: '/client-relations/sales', icon: BriefcaseBusiness, permission: 'manage sales' },
    ],
  },
  {
    label: 'Bookings',
    icon: CalendarCheck2,
    children: [
      { label: 'Reservations', route: 'bookings.reservations', path: '/bookings/reservations', icon: BookOpenCheck, permission: 'manage reservations' },
      { label: 'Blocks', route: 'bookings.blocks', path: '/bookings/blocks', icon: CalendarRange, permission: 'manage blocks' },
      { label: 'Events', route: 'bookings.events', path: '/bookings/events', icon: CalendarDays, permission: 'manage events' },
    ],
  },
  {
    label: 'Front Desk',
    icon: ConciergeBell,
    children: [
      { label: 'Arrivals', route: 'front-desk.arrivals', path: '/front-desk/arrivals', icon: LogIn, permission: 'view arrivals' },
      { label: 'In-House', route: 'front-desk.in-house', path: '/front-desk/in-house', icon: BedDouble, permission: 'view in-house' },
      { label: 'Departures', route: 'front-desk.departures', path: '/front-desk/departures', icon: LogOut, permission: 'view departures' },
      { label: 'Workspace', route: 'front-desk.workspace', path: '/front-desk/workspace', icon: Monitor, permission: 'manage front desk workspace' },
    ],
  },
  {
    label: 'Inventory & Rooms',
    icon: Hotel,
    children: [
      { label: 'Room Management', route: 'inventory.room-management', path: '/inventory-rooms/room-management', icon: DoorOpen, permission: 'manage rooms' },
      { label: 'Housekeeping', route: 'inventory.housekeeping', path: '/inventory-rooms/housekeeping', icon: Sparkles, permission: 'manage housekeeping' },
      { label: 'Restrictions', route: 'inventory.restrictions', path: '/inventory-rooms/restrictions', icon: Ban, permission: 'manage restrictions' },
    ],
  },
  {
    label: 'Financials',
    icon: Wallet,
    children: [
      { label: 'Accounts Receivable', route: 'financials.accounts-receivable', path: '/financials/accounts-receivable', icon: Receipt, permission: 'manage ar' },
      { label: 'Cashiering', route: 'financials.cashiering', path: '/financials/cashiering', icon: Landmark, permission: 'manage cashiering' },
      { label: 'End of Day', route: 'financials.end-of-day', path: '/financials/end-of-day', icon: MoonStar, permission: 'run night audit' },
      { label: 'Comp Accounting', route: 'financials.comp-accounting', path: '/financials/comp-accounting', icon: CircleDollarSign, permission: 'manage comp accounting' },
    ],
  },
  {
    label: 'Reports & Analytics',
    icon: BarChart3,
    children: [
      {
        label: 'Reports',
        icon: FileText,
        children: [
          { label: '📥 Deposits', route: 'reports.deposits', path: '/reports/deposits', icon: Download, permission: 'view deposits report' },
          { label: '📤 Withdraws', route: 'reports.withdraws', path: '/reports/withdraws', icon: Upload, permission: 'view withdraws report' },
          { label: '🛡️ Safe Movement Report', route: 'reports.safe-movement', path: '/reports/safe-movement', icon: Shield, permission: 'view safe movement report' },
          { label: '👥 Customer Movement', route: 'reports.customer-movement', path: '/reports/customer-movement', icon: UsersRound, permission: 'view customer movement report' },
          { label: '🛎️ Services Report', route: 'reports.services', path: '/reports/services', icon: BellRing, permission: 'view services report' },
          { label: '📅 Monthly Report', route: 'reports.monthly', path: '/reports/monthly', icon: Calendar, permission: 'view monthly report' },
          { label: '🏢 Units Movement Report', route: 'reports.units-movement', path: '/reports/units-movement', icon: Building2, permission: 'view units movement report' },
          { label: '📊 Occupancy Ratio', route: 'reports.occupancy-ratio', path: '/reports/occupancy-ratio', icon: PieChart, permission: 'view occupancy ratio report' },
          { label: '🧹 Cleaning Movement', route: 'reports.cleaning-movement', path: '/reports/cleaning-movement', icon: BrushCleaning, permission: 'view cleaning movement report' },
          { label: '🛠️ Maintenance Movement', route: 'reports.maintenance-movement', path: '/reports/maintenance-movement', icon: Wrench, permission: 'view maintenance movement report' },
          { label: '🔄 Reservation Transfers', route: 'reports.reservation-transfers', path: '/reports/reservation-transfers', icon: RefreshCcw, permission: 'view reservation transfers report' },
          { label: '⚖️ Revenues & Taxes', route: 'reports.revenues-taxes', path: '/reports/revenues-taxes', icon: Scale, permission: 'view revenues taxes report' },
          { label: '📅 Reservation Resources', route: 'reports.reservation-resources', path: '/reports/reservation-resources', icon: Calendar, permission: 'view reservation resources report' },
          { label: '📄 Employee Contracts', route: 'reports.employee-contracts', path: '/reports/employee-contracts', icon: FileBadge, permission: 'view employee contracts report' },
          { label: '🧾 Invoices Report', route: 'reports.invoices', path: '/reports/invoices', icon: Receipt, permission: 'view invoices report' },
          { label: '☀️ Daily report', route: 'reports.daily', path: '/reports/daily', icon: Sun, permission: 'view daily report' },
        ],
      },
    ],
  },
  {
    label: 'Miscellaneous',
    icon: Boxes,
    children: [
      { label: 'Exports', route: 'misc.exports', path: '/misc/exports', icon: Download, permission: 'manage exports' },
      { label: 'Interfaces', route: 'misc.interfaces', path: '/misc/interfaces', icon: Cable, permission: 'manage interfaces' },
      { label: 'Service Requests', route: 'misc.service-requests', path: '/misc/service-requests', icon: LifeBuoy, permission: 'manage service requests' },
    ],
  },
  {
    label: 'Settings',
    icon: Settings,
    children: [
      { label: 'Header & Slider', route: 'settings.header-slider', path: '/settings/header-slider', icon: SlidersHorizontal, permission: 'manage header slider settings' },
      { label: 'General Settings', route: 'settings.general', path: '/settings/general', icon: Cog, permission: 'manage general settings' },
      { label: 'Facility Settings', route: 'settings.facility', path: '/settings/facility', icon: Building, permission: 'manage facility settings' },
      { label: 'Hotel Amenities', route: 'settings.hotel-amenities', path: '/settings/hotel-amenities', icon: Bath, permission: 'manage hotel amenities settings' },
      { label: 'Integration Settings', route: 'settings.integration', path: '/settings/integration', icon: Plug, permission: 'manage integration settings' },
      { label: 'Users And Roles', route: 'settings.users-roles', path: '/settings/users-roles', icon: UserCog, permission: 'manage users and roles settings' },
      { label: 'Document Settings', route: 'settings.document', path: '/settings/document', icon: FileCheck2, permission: 'manage document settings' },
      { label: 'Notifications Settings', route: 'settings.notifications', path: '/settings/notifications', icon: Bell, permission: 'manage notifications settings' },
      { label: 'Finance Settings', route: 'settings.finance', path: '/settings/finance', icon: HandCoins, permission: 'manage finance settings' },
      { label: 'Activity Logs', route: 'settings.activity-logs', path: '/settings/activity-logs', icon: ClipboardList, permission: 'view activity logs settings' },
      { label: 'Ledger Numbers', route: 'settings.ledger-numbers', path: '/settings/ledger-numbers', icon: Hash, permission: 'manage ledger numbers settings' },
      { label: 'Reservation Resource Settings', route: 'settings.reservation-resource', path: '/settings/reservation-resource', icon: Calendar, permission: 'manage reservation resource settings' },
      { label: 'Customer Groups Settings', route: 'settings.customer-groups', path: '/settings/customer-groups', icon: Link, permission: 'manage customer groups settings' },
      { label: 'Website Settings', route: 'settings.website', path: '/settings/website', icon: Globe, permission: 'manage website settings' },
      { label: 'Rating Settings', route: 'settings.rating', path: '/settings/rating', icon: Star, permission: 'manage rating settings' },
      { label: 'Services Included In The Price', route: 'settings.services-included', path: '/settings/services-included', icon: BellRing, permission: 'manage included services settings' },
      { label: 'Maintenance Settings', route: 'settings.maintenance', path: '/settings/maintenance', icon: Hammer, permission: 'manage maintenance settings' },
    ],
  },
];

export const flattenSidebarRoutes = (nodes = sidebarConfig, list = []) => {
  nodes.forEach((node) => {
    if (node.path && node.route) list.push(node);
    if (node.children?.length) flattenSidebarRoutes(node.children, list);
  });
  return list;
};
